### ISSUE TITLE
Use sha256 instead of sha1

### ISSUE THREAD

**Issue by RobertAudi** [1egoman/homebrew-tap#1]
`sha1` has been deprecated. For some reason, you switched from `sha256` to `sha1` in this commit: 222dc0215ae0e40b69a2d8656db5203cca341a7c.

At the moment `brew` just shows a warning, but it might throw an error at some point in the (near) future.

```
Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/1egoman/homebrew-tap/biome.rb:6:in `<class:Biome>'
Please report this to the 1egoman/tap tap!
```

**Comment by 1egoman** [comment]
@RobertAudi It was part of a troubleshooting step, and I never switched it back. Good point though - I just merged in a fix (#2).

Thanks for pointing this out!
